config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  resources :reactions do
    member do
        put "like", to:    "reactions#upvote"
        put "dislike", to: "reactions#downvote"
      end
    end
  devise_for :users
  resources :users
  resources :debats do
    member do
      put "like", to:    "debats#upvote"
      put "dislike", to: "debats#downvote"
    end
    resources :reactions
  end
  root "debats#index"
  
  

end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def create
    @debat = Debat.find(params[:debat_id])
    @reaction = @debat.reactions.new(reaction_params)
    @reaction.user = current_user

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to @debat, notice: 'Reaction was successfully created.' }
        format.json { render json: @reaction, status: :created, location: @reaction }
      else
        format.html { render action: "new" }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1
  # DELETE /reactions/1.json
  def destroy
    @reaction.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Reaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def upvote
    @reaction = Reaction.find(params[:id])
    @reaction.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @reaction = Reaction.find(params[:id])
    @reaction.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reaction_params
      params.require(:reaction).permit(:debat_id, :body, :user_id)
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_for(@reaction) do |f| %>
  <% if @reaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

      <ul>
      <% @reaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :debat_id %><br>
    <%= f.number_field :debat_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reactions/_reaction.html.erb
<%= div_for(reaction) do %>
	<div class="comments_wrapper">
			<div class="said">By <span class="comaut"><strong><%= link_to reaction.user.name, reaction.user %></strong></span><span class="auteur"> - submitted <%= time_ago_in_words(reaction.created_at) %> ago</span></div>
			<div class="content"><%= reaction.body %></div>
          	
	  			<%= link_to like_reaction_path(reaction), method: :put do %>
	  				<span class="oui"><i class="fa fa-angle-up"></i>Agree</span>
	  				<span class="ouicount"><%= reaction.get_upvotes.size %></span> 
	  			<% end %>
	  		
	  			<%= link_to dislike_reaction_path(reaction), method: :put do %>
	  				<span class="non"><i class="fa fa-angle-down"></i> Don't agree</span>
	  				<span class="noncount"><%= reaction.get_downvotes.size %></span> 
	  			<% end %>
    
			<% if reaction.user == current_user %>
				- <span class="destroy"><%= link_to 'Delete',reaction, method: :delete, data: { confirm: 'Are you sure?' } %></span>
			<% end %>
	</div>
<% end %>

app/views/reactions/edit.html.erb
<h1>Editing Reaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @reaction %> |
<%= link_to 'Back', reactions_path %>

app/views/reactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reactions</h1>

<table>
  <thead>
    <tr>
      <th>Debat</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reactions.each do |reaction| %>
      <tr>
        <td><%= reaction.debat_id %></td>
        <td><%= reaction.body %></td>
        <td><%= reaction.user %></td>
        <td><%= link_to 'Show', reaction %></td>
        <td><%= link_to 'Edit', edit_reaction_path(reaction) %></td>
        <td><%= link_to 'Destroy', reaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reaction', new_reaction_path %>

app/views/reactions/new.html.erb
<h1>New Reaction</h1>

<%= render 'form' %>

<%= link_to 'Back', reactions_path %>

app/views/reactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Debat:</strong>
  <%= @reaction.debat_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @reaction.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @reaction.user %>
</p>

<%= link_to 'Edit', edit_reaction_path(@reaction) %> |
<%= link_to 'Back', reactions_path %>