config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  resources :reactions do
    member do
        put "like", to:    "reactions#upvote"
        put "dislike", to: "reactions#downvote"
      end
    end
  devise_for :users
  resources :users
  resources :debats do
    member do
      put "like", to:    "debats#upvote"
      put "dislike", to: "debats#downvote"
    end
    resources :reactions
  end
  root "debats#index"
  
  

end

app/models/debat.rb
class Debat < ActiveRecord::Base

    acts_as_votable
    belongs_to :user
    has_many :reactions, :dependent => :destroy
    def to_param
        "#{id} #{title}".parameterize
    end
    def self.search(search)
        where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
    end
end

app/controllers/debats_controller.rb
class DebatsController < ApplicationController
  before_action :set_debat, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  helper_method :sort_column, :sort_direction

  # GET /debats
  # GET /debats.json
  def index
    
    @user = current_user
    if params[:search]
     @debats = Debat.search(params[:search]).order("#{sort_column} #{sort_direction}").page(params[:page]).per_page(10)
    else
      @debats = Debat.order("#{sort_column} #{sort_direction}").page(params[:page]).per_page(10)
    end
  end

  # GET /debats/1
  # GET /debats/1.json
  def show
    @reactionh = Reaction.highest_voted.limit(3)
  end

  # GET /debats/new
  def new
    @debat = current_user.debats.build
  end

  # GET /debats/1/edit
  def edit
  end

  # POST /debats
  # POST /debats.json
  def create
    @debat = current_user.debats.build(debat_params)

    respond_to do |format|
      if @debat.save
        format.html { redirect_to @debat, notice: 'Debat was successfully created.' }
        format.json { render :show, status: :created, location: @debat }
      else
        format.html { render :new }
        format.json { render json: @debat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debats/1
  # PATCH/PUT /debats/1.json
  def update
    respond_to do |format|
      if @debat.update(debat_params)
        format.html { redirect_to @debat, notice: 'Debat was successfully updated.' }
        format.json { render :show, status: :ok, location: @debat }
      else
        format.html { render :edit }
        format.json { render json: @debat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debats/1
  # DELETE /debats/1.json
  def destroy
    @debat.destroy
    respond_to do |format|
      format.html { redirect_to debats_url, notice: 'Debat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
      @debat = Debat.find(params[:id])
      @debat.upvote_by current_user
        respond_to do |format|
          format.html {redirect_to :back }
          format.json { render json: { count: @debat.liked_count } }
          if user_signed_in?
            format.js { render :layout => false }
          end
        end
  end
  
  def downvote
    @debat = Debat.find(params[:id])
    @debat.downvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @debat.disliked_count } }
      if user_signed_in?
      format.js   { render :layout => false }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debat
      @debat = Debat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debat_params
      params.require(:debat).permit(:title, :description)
    end
    
    def sortable_columns
    ["created_at", "cached_votes_total"]
    end

    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "cached_votes_total"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/debats_helper.rb
module DebatsHelper
    def sort_link(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "desc" ? "asc" : "desc"
        icon = sort_direction == "asc" ? "fa fa-chevron-up" : "fa fa-chevron-down"
        icon = column == sort_column ? icon : ""
        link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
    end
end

app/views/debats/_debats.erb
<% @debats.each do |debat| %>
        <div class="row">
        <div class="large-1 columns count">
          <span class= "like-<%= debat.id %>">
            <% if user_signed_in? %>
              <%= link_to like_debat_path(debat), method: :put, remote: true do %>
                <div class="upcount"><i class="fa fa-angle-up"></i></div>
                <div class="ouicount up-<%= debat.id %>"><%= debat.get_upvotes.size %></div>
                <div class="oui">Oui</div>
              <%end%>
            <% else %>
              <%= link_to like_debat_path(debat), method: :put do %>
                <div class="upcount"><i class="fa fa-angle-up"></i></div>
                <div class="ouicount up-<%= debat.id %>"><%= debat.get_upvotes.size %></div>
                <div class="oui">Oui</div>
              <%end%>
            <% end %>
          </span>
            
          <span class= "dislike-<%= debat.id %>">
            <% if user_signed_in? %> 
              <%= link_to dislike_debat_path(debat), method: :put, remote: true do %>
                <div class="non">Non</div>
                <div class="noncount down-<%= debat.id%>"> <%= debat.get_downvotes.size %></div>
                <div class="downcount"><i class="fa fa-angle-down"></i></div>
              <% end %>
            <% else %>
              <%= link_to dislike_debat_path(debat), method: :put do %>
                <div class="non">Non</div>
                <div class="noncount down-<%= debat.id%>"> <%= debat.get_downvotes.size %></div>
                <div class="downcount"><i class="fa fa-angle-down"></i></div>
              <% end %>
            <% end %>
          </span>
        </div>
        
        <div class="large-9 medium-9 small-12 columns">
          <div class="debat"><%= debat.title %></div>
          <div class="auteur">Submitted <%= time_ago_in_words(debat.created_at) %> ago by <span class="pseudo">blabla</span></div> 
        </div>
        
        <div class="small-2 columns opinion">
          <div class="opincount">514  opinions</div>
          <div class="reagir">Réagir</div>
        </div>
        
      </div>
          <%#= link_to 'Show', debat %>
          <%#= link_to 'Edit', edit_debat_path(debat) %>
          <%#= link_to 'Destroy', debat, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

app/views/debats/_debats.html.erb
<% @debats.each do |debat| %>
      <div class="row debates">
        <div class="small-1 columns count">
          <span class= "like-<%= debat.id %>">
            <% if user_signed_in? %>
              <%= link_to like_debat_path(debat), method: :put, remote: true do %>
                <% if current_user.voted_up_on? debat %>
                  <div class="upcountsign upc-<%= debat.id %>"><i class="fa fa-angle-up"></i></div>
                <% else %>
                  <div class="upcount upc-<%= debat.id %>"><i class="fa fa-angle-up"></i></div>
                <% end %>
                <div class="ouicount up-<%= debat.id %>"><%= debat.get_upvotes.size %></div>
                <div class="oui">Yes</div>
              <% end %>
            <% else %>
              <%= link_to like_debat_path(debat), method: :put do %>
                <div class="upcount"><i class="fa fa-angle-up"></i></div>
                <div class="ouicount up-<%= debat.id %>"><%= debat.get_upvotes.size %></div>
                <div class="oui">Yes</div>
              <% end %>
            <% end %>
          </span>
            
          <span class= "dislike-<%= debat.id %>">
            <% if user_signed_in? %> 
              <%= link_to dislike_debat_path(debat), method: :put, remote: true do %>
                <div class="non">No</div>
                <div class="noncount down-<%= debat.id%>"> <%= debat.get_downvotes.size %></div>
                <% if current_user.voted_down_on? debat %>
                  <div class="downcountsign doc-<%= debat.id %>"><i class="fa fa-angle-down"></i></div>
                <% else %>
                  <div class="downcount doc-<%= debat.id %>"><i class="fa fa-angle-down"></i></div>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to dislike_debat_path(debat), method: :put do %>
                <div class="non">No</div>
                <div class="noncount down-<%= debat.id%>"> <%= debat.get_downvotes.size %></div>
                <div class="downcount doc-<%= debat.id %>"><i class="fa fa-angle-down"></i></div>
              <% end %>
            <% end %>
          </span>
        </div>
        
        <div class="large-9 medium-9 small-12 columns">
          <div class="debat"><%= link_to debat.title, debat %></div>
          <div class="auteur">Submitted <%= time_ago_in_words(debat.created_at) %> ago by <span class="pseudo"><%= link_to debat.user.name, debat.user %></span> <% if debat.reactions.size > 0 %> -  <span class="black"> <%= link_to "Last opinion given", debat %> <%= link_to time_ago_in_words(debat.reactions.last.created_at), debat %> ago </span> <% end %></div>
          <div class="countresp">
          	<span class= "like-<%= debat.id %>">
          		<% if user_signed_in? %>
          			<%= link_to like_debat_path(debat), method: :put, remote: true do %>
          				<span class="oui"><i class="fa fa-angle-up"></i> Oui</span>
          				<span class="ouicount up-<%= debat.id %>"><%= debat.get_upvotes.size %></span> 
          			<% end %>
          		<% else %>
          			<%= link_to like_debat_path(debat), method: :put do %>
          				<span class="oui"><i class="fa fa-angle-up"></i> Oui</span>
          				<span class="ouicount up-<%= debat.id %>"><%= debat.get_upvotes.size %></span> 
          			<% end %>
          		<% end %>
          	</span>
          
          	<span class= "dislike-<%= debat.id %>">
          		<% if user_signed_in? %>
          			<%= link_to dislike_debat_path(debat), method: :put, remote: true do %>
          				<span class="non"><i class="fa fa-angle-down"></i> Non</span> 
          				<span class="noncount down-<%= debat.id%>"><%= debat.get_downvotes.size %></span> 
          			<% end %>
          		<%else%>
          			<%= link_to dislike_debat_path(debat), method: :put do %>
          				<span class="non"><i class="fa fa-angle-down"></i> Non</span> 
          				<span class="noncount down-<%= debat.id%>"><%= debat.get_downvotes.size %></span> 
          			<% end %>
          		<%end%>
          	</span>
          
          	<span class="opincount"> <%= debat.reactions.count %> opinions </span> 
            </div>
          </div> 
        
        <div class="small-2 columns opinion">
          <div class="opincount"><%= debat.reactions.count %>  opinions</div>
          <div class="reagir"><%= link_to 'Give your opinion', debat %></div>
        </div>
        
      </div>
          <%#= link_to 'Show', debat %>
          <%#= link_to 'Edit', edit_debat_path(debat) %>
          <%#= link_to 'Destroy', debat, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/debats/_form.html.erb
<%= form_for(@debat) do |f| %>
  <% if @debat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debat.errors.count, "error") %> prohibited this debat from being saved:</h2>

      <ul>
      <% @debat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="row">
  <div class="large-4 large-centered columns">
    <div class="actions">
      <%= f.submit "Submit", class:"signbutton button" %>
    </div>
  </div>
  </div>
<% end %>

app/views/debats/downvote.js.erb
$( document ).ready(function() {
<% if current_user.voted_down_on? @debat %>
   $('.doc-<%= @debat.id %>').css('color', '#ff7743');
   $('.upc-<%= @debat.id %>').css('color', '#9696A0');
<% end %>
});


$('.dislike-<%= @debat.id %>').bind('ajax:success', function() {

   $('.up-<%= @debat.id %>').text(<%= @debat.get_upvotes.size%>);
   $('.down-<%= @debat.id %>').text(<%= @debat.get_downvotes.size%>);

});

app/views/debats/edit.html.erb
<h1>Editing Debat</h1>

<%= render 'form' %>

<%= link_to 'Show', @debat %> |
<%= link_to 'Back', debats_path %>

app/views/debats/index.html.erb
<div class="row menugroup">
      <div class="row">
        <div class="large-2 columns">
          <span class="lang"><%= link_to 'Create a debate', new_debat_path %></span>
        </div>
    
        
        <div class="large-8 columns" id="menubox">
            <%= sort_link "cached_votes_total", "By Popularity" %>
            <%= sort_link "created_at", "By Date" %>
        </div>
      </div>
      
      <div class="row">
        <div class="medium-3 columns">
          <%= form_tag(debats_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Debates " %>
          <% end %>
        </div>
      </div>
</div>




<div id="products">
  <% if @debats.present? %>
    <%= render "debats" %>
  <% else %>
    <p>There are no debates containing the term(s) <%= params[:search] %>.</p>
<% end %>
</div>

<%= will_paginate @debats %>


<div class="row footer">
  <div class="large-12 columns">
    <span class="arrow"><%= link_to ' <i class="fa fa-arrow-up"></i>'.html_safe %></span>
  </div>
</div>         
       
      
       
<br>

app/views/debats/index.js.erb
$('#products').append('<%= j render "debats" %>');
<% if @debats.next_page %>
	$('.pagination').replaceWith('<%= will_paginate(@debats) %>');
<% else %>
	$('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/debats/new.html.erb
<div class="large-8 large-centered columns">
<h2 class="sign">New Debate</h2>

<%= render 'form' %>

<div class="back"><i class="fa fa-arrow-left"></i> <%= link_to "Back", :back %></div>
</div>

app/views/debats/show.html.erb
<div class="under">
<div class="row">
  <div class="likeshow">
    <div class="small-1 columns count">
      <span class= "like-<%= @debat.id %>">
        <% if user_signed_in? %>
          <%= link_to like_debat_path(@debat), method: :put, remote: true do %>
            <% if current_user.voted_up_on? @debat %>
              <div class="upcountsign upc-<%= @debat.id %>"><i class="fa fa-angle-up"></i></div>
            <% else %>
              <div class="upcount upc-<%= @debat.id %>"><i class="fa fa-angle-up"></i></div>
            <% end %>
            <div class="ouicount up-<%= @debat.id %>"><%= @debat.get_upvotes.size %></div>
            <div class="oui">Yes</div>
          <% end %>
        <% else %>
          <%= link_to like_debat_path(@debat), method: :put do %>
            <div class="upcount"><i class="fa fa-angle-up"></i></div>
            <div class="ouicount up-<%= @debat.id %>"><%= @debat.get_upvotes.size %></div>
            <div class="oui">Yes</div>
          <% end %>
        <% end %>
      </span>
        
      <span class= "dislike-<%= @debat.id %>">
        <% if user_signed_in? %> 
          <%= link_to dislike_debat_path(@debat), method: :put, remote: true do %>
            <div class="non">No</div>
            <div class="noncount down-<%= @debat.id%>"> <%= @debat.get_downvotes.size %></div>
            <% if current_user.voted_down_on? @debat %>
              <div class="downcountsign doc-<%= @debat.id %>"><i class="fa fa-angle-down"></i></div>
            <% else %>
              <div class="downcount doc-<%= @debat.id %>"><i class="fa fa-angle-down"></i></div>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to dislike_debat_path(@debat), method: :put do %>
            <div class="non">No</div>
            <div class="noncount down-<%= @debat.id%>"> <%= @debat.get_downvotes.size %></div>
            <div class="downcount doc-<%= @debat.id %>"><i class="fa fa-angle-down"></i></div>
          <% end %>
        <% end %>
      </span>
    </div>
  </div>
  
  <div class="large-8 columns middle">
    <div class="debatshow"><%= @debat.title %></div>
    <div class="desc"><%= @debat.description %></div>
    <div class="auteur">Submitted <%= time_ago_in_words(@debat.created_at) %> ago by <span class="pseudo"><%= link_to @debat.user.name, @debat.user %></span></div>
    <div class="reactshow">
    <div class="opishow"><%= @debat.reactions.count %> Opinions<br/></div>
    <%= render :partial => @debat.reactions %>
    </div>
    <div class="row">
      <div class="large-12 columns">
        <div class="showform">
          <%= simple_form_for [@debat, Reaction.new]  do |f| %>
            <%= f.text_area :body %>
            <div class="row">
              <div class="large-4 columns">
                <%= f.submit "Add Comment", class: "button signbutton" %> 
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="large-3 columns sidebar">
    <% if @debat.reactions.count <= 3 %>
      And you what do you think?
  
    <%elsif @debat.reactions.count > 3 %>

    <div class="best">Top 3 Best Opinions:</div>
    
     <% @reactionh.each do |bestopin| %>
      <div class="bestcontent">
       <%= bestopin.body %><br>
       <div class="auteur">by <span class="pseudo"><%= link_to bestopin.user.name, bestopin.user %></span></div>
      </div>
     <% end %>
   
  </div>
  <% end %>
</div>
</div>

app/views/debats/upvote.js.erb
$( document ).ready(function() {
<% if current_user.voted_up_on? @debat %>
   $('.upc-<%= @debat.id %>').css('color', '#ff7743');
   $('.doc-<%= @debat.id %>').css('color', '#9696A0');
<% end %>
});



$('.like-<%= @debat.id %>').bind('ajax:success', function() {

   $('.up-<%= @debat.id %>').text(<%= @debat.get_upvotes.size%>);
   $('.down-<%= @debat.id %>').text(<%= @debat.get_downvotes.size%>);

});